config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get 'foo_bar_baz/index'

  devise_for :users, class_name: 'UserForm', controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', to: 'omniauth_callbacks#setup'
  end

  get 'sitemap' => 'sitemaps#index'

  resources :interviews, only: %i(index show)
  resources :sitemaps, only: %i(index)
  resources :conferences, only: %i(index show)
  resources :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', as: :signin
  get '/signout' => 'sessions#destroy', as: :signout
  get '/auth/failure' => 'sessions#failure'

  root to: 'interviews#index'

  # last rule for unmatched requests
  get '*unmatched_route', to: 'errors#intercept_404'
end

# == Route Map
#
#                   Prefix Verb     URI Pattern                             Controller#Action
#        foo_bar_baz_index GET      /foo_bar_baz/index(.:format)            foo_bar_baz#index
#         new_user_session GET      /users/sign_in(.:format)                devise/sessions#new
#             user_session POST     /users/sign_in(.:format)                devise/sessions#create
#     destroy_user_session DELETE   /users/sign_out(.:format)               devise/sessions#destroy
#  user_omniauth_authorize GET|POST /users/auth/:provider(.:format)         omniauth_callbacks#passthru {:provider=>/google_oauth2/}
#   user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)  omniauth_callbacks#:action
#            user_password POST     /users/password(.:format)               devise/passwords#create
#        new_user_password GET      /users/password/new(.:format)           devise/passwords#new
#       edit_user_password GET      /users/password/edit(.:format)          devise/passwords#edit
#                          PATCH    /users/password(.:format)               devise/passwords#update
#                          PUT      /users/password(.:format)               devise/passwords#update
# cancel_user_registration GET      /users/cancel(.:format)                 registrations#cancel
#        user_registration POST     /users(.:format)                        registrations#create
#    new_user_registration GET      /users/sign_up(.:format)                registrations#new
#   edit_user_registration GET      /users/edit(.:format)                   registrations#edit
#                          PATCH    /users(.:format)                        registrations#update
#                          PUT      /users(.:format)                        registrations#update
#                          DELETE   /users(.:format)                        registrations#destroy
#    user_omniauth_upgrade GET      /users/auth/:provider/upgrade(.:format) omniauth_callbacks#upgrade
#                          GET      /users/auth/:provider/setup(.:format)   omniauth_callbacks#setup
#                  sitemap GET      /sitemap(.:format)                      sitemaps#index
#               interviews GET      /interviews(.:format)                   interviews#index
#                interview GET      /interviews/:id(.:format)               interviews#show
#                 sitemaps GET      /sitemaps(.:format)                     sitemaps#index
#              conferences GET      /conferences(.:format)                  conferences#index
#               conference GET      /conferences/:id(.:format)              conferences#show
#                    users GET      /users(.:format)                        users#index
#                          POST     /users(.:format)                        users#create
#                 new_user GET      /users/new(.:format)                    users#new
#                edit_user GET      /users/:id/edit(.:format)               users#edit
#                     user GET      /users/:id(.:format)                    users#show
#                          PATCH    /users/:id(.:format)                    users#update
#                          PUT      /users/:id(.:format)                    users#update
#                          DELETE   /users/:id(.:format)                    users#destroy
#              rails_admin          /admin                                  RailsAdmin::Engine
#                          GET      /auth/:provider/callback(.:format)      sessions#create
#                   signin GET      /signin(.:format)                       sessions#new
#                  signout GET      /signout(.:format)                      sessions#destroy
#             auth_failure GET      /auth/failure(.:format)                 sessions#failure
#                     root GET      /                                       interviews#index
#                          GET      /*unmatched_route(.:format)             errors#intercept_404
#
# Routes for RailsAdmin::Engine:
#     dashboard GET         /                                      rails_admin/main#dashboard
#         index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#           new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#        export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
#   bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# history_index GET         /:model_name/history(.:format)         rails_admin/main#history_index
#   bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#          show GET         /:model_name/:id(.:format)             rails_admin/main#show
#          edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#        delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
#   show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app
#  history_show GET         /:model_name/:id/history(.:format)     rails_admin/main#history_show
#

app/controllers/interviews_controller.rb
# frozen_string_literal: true
class InterviewsController < ApplicationController
  def index
    @interviews = if params[:q].present?

                    @query = params[:q].strip
                    @header_title = "Interview Search: \"#{@query}\""

                    found_ids = PgSearch
                                .multisearch(@query)
                                .where(searchable_type: 'YouTube::Video')
                                .uniq
                                .pluck(:searchable_id)
                                .sort

                    YouTube::Video
                      .includes(:conference)
                      .published
                      .where('you_tube_videos.id in (?)', found_ids)
                      .order(id: 'asc')

                  else
                    YouTube::Video
                      .includes(:conference)
                      .published.order('priority desc, id asc')
                  end
  end

  def show
    @interview = YouTube::Video.friendly.find(params[:id])
  end
end

app/helpers/interviews_helper.rb
# frozen_string_literal: true
module InterviewsHelper
  def title_for_interview(you_tube_video)
    if you_tube_video.at_conference?
      "Interview with #{you_tube_video.interviewee_names} @ #{you_tube_video.conference_name} #{you_tube_video.conference.city} #{you_tube_video.conference_year}"
    else
      "Interview with #{you_tube_video.interviewee_names}"
    end
  end
end

app/views/interviews/index.html.erb
<% meta title: 'WHOIS Tech Community', description: 'Interviews with user-group and conference organizers, F/OSS contributors, noted authors, speakers and other tech community influencers.' %>

<div class="twelve columns header_nav_fullwidth">
  <%= render 'shared/header' %>
</div>

<div class="twelve columns" >
  <h1 id="header_title"><%= @header_title || 'All Interviews' %></h1>
    <%= form_tag interviews_path, method: :get, remote: true do %>
      <input tabindex="0" autofocus type="search" placeholder="Filter interviews" id="q" name="q" style="display: inline-block;" value="<%= @query %>">
    <% end %>
</div>

<div class="twelve columns">
  <div id="container">
    <% @interviews.each do |interview| %>

      <% cache interview do %>
        <div class='box photo col2'>
          <%= link_to interview_path(interview) do %>
            <%= image_tag(interview.thumbnail('medium').url, 'data-caption' => interview.title, size: "#{interview.thumbnail('medium').width}x#{interview.thumbnail('medium').height}", alt: interview.title, class: 'video_thumbnail') %>
          <% end %>
          <h4><strong><%= interview.interviewee_names %></strong></h4>
          <% if interview.subtitle.present? %>
            <h5 class="box-subtitle"><%= interview.subtitle %></h5>
          <% end %>
          <p><%= truncate(strip_tags(MARKDOWN.render(interview.description)), length: 140, omission: '…') %></p>
          <% if interview.at_conference? %>
            <div class="box_comment conference"><p><%= link_to "#{interview.conference_name} #{interview.conference_city} #{interview.conference_year}", interview.conference %></p></div>
          <% end %>
        </div>
      <% end %>

    <% end %>
  </div>
  <%= render 'shared/footer' %>
</div>

<script src="/javascripts/foundation.min.js" type="text/javascript"></script>

<script src="/javascripts/app.js" type="text/javascript"></script>
<script src="/javascripts/masonry.js" type="text/javascript"></script>

<script type="text/javascript">
  $(function(){
    var $container = $('#container');
    $container.imagesLoaded(function() { $container.masonry({itemSelector : '.box', isFitWidth: true, isAnimated: true}); });
  });
</script>

app/views/interviews/show.html.erb
<%
    meta \
      title: title_for_interview(@interview),
      twitter: {
        card: :summary,
        site: '@ugtastic',
        title: title_for_interview(@interview),
        domain: 'ugtastic.com',
        description: @interview.subtitle
      }
%>

<%- content_for :canonical_tag do -%>
  <link rel='canonical' href="<%= interview_url(@interview, host: 'www.ugtastic.com', protocol: 'https://') -%>" />
<%- end -%>

<div class="row page_wrap" style="margin-top:-2px">
  <div class="twelve columns">
    <div class="row">
      <div class="twelve columns header_nav" style="margin-bottom:0; box-shadow: none">
        <div class="twelve columns">
          <%= render 'shared/navigation' %>
        </div>
      </div>
    </div>

    <div class="heading_dots" style="margin-bottom:15px">
      <h1 class="<%= @interview.interviewee_names.length >= 32 ? 'heading_largesize' : 'heading_supersize' %>">
        <span class="heading_center_bg"><%= @interview.interviewee_names %></span>
      </h1>
    </div>

    <div class="row">
      <div class="flex-video widescreen">
        <iframe
          id="ytplayer"
          type="text/html"
          width="640"
          height="390"
          src="https://www.youtube.com/embed/<%= @interview.remote_video_id %>?cc_load_policy=1&enablejsapi=1&modestbranding=1&playsinline=1&autohide=1&color=white&theme=light&origin=<%= ENV['YOUTUBE_EMBED_ORIGIN'] %>"
          frameborder="0"
          allowfullscreen></iframe>
      </div>
    </div>

    <% if @interview.subtitle.present? %>
      <h4>
        <%= @interview.subtitle %>
        <% if @interview.at_conference? %>
          <strong>@</strong>
          <%= @interview.conference_name %> <%= @interview.conference.city %> <%= @interview.conference_year %>
        <% end %>
      </h4>
    <% end %>

    <div class="row">
      <div class="twelve columns">

        <dl class="tabs two-up">
          <dd class="active"><a href="#simple1">Description</a></dd>

          <% @interview.transcripts.each_with_object(1) do |transcript, i| %>
            <dd><a href="#simple<%= i += 1 %>"><%= "Transcript #{transcript.using_default_locale? ? '' : "(#{transcript.locale})" }" %></a></dd>
          <% end %>
        </dl>

        <ul class="tabs-content">
          <li class="active" id="simple1Tab">
            <%= raw(MARKDOWN.render(@interview.description)) %>
          </li>

          <% @interview.transcripts.each_with_object(1) do |transcript, i| %>
            <li id="simple<%= i += 1 %>Tab">
              <%= raw(MARKDOWN.render(transcript.text)) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>


    <div class="row">
      <div class="twelve columns">
        <ul id="menu3" class="footer_menu horizontal">
          <li class="">
            <a href="/">Home</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<script src="/javascripts/foundation.min.js" type="text/javascript"></script>
<script src="/javascripts/app.js" type="text/javascript"></script>